/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mtaketani.crypto;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CryptTest {
    @Test
    void 暗号化復号化で元に戻るかのテスト() {
        String encryptoText = CryptoAes.encrypto("test");
        String decryptoText = CryptoAes.decrypto(encryptoText);
        assertEquals("test", decryptoText);
    }
}
